---
version: 3
images:
  base_image:
    name: docker.io/redhat/ubi9:latest
dependencies:
  galaxy:
    collections:
      - type: git
        name: https://github.com/redhat-cop/cloud.vmware_ops.git
  python: requirements.txt
  ansible_core:
    package_pip: ansible-core>=2.15.0
  ansible_runner:
    package_pip: ansible-runner

additional_build_steps:
  prepend_base: RUN $PKGMGR install -y git
