collections:
- name: kubernetes.core
- name: community.general
- name: amazon.aws
- name: containers.podman
- name: sabre1041.eda
- name: community.crypto
- name: cloud.vmware_ops
  #source: https://hhwjd-aap.apps.cluster-hhwjd.hhwjd.sandbox60.opentlc.com/pulp_ansible/galaxy/validated/


