---
- name: Import Collection Level Vars
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../../vars/main.yml"

- name: Validate Inputs
  ansible.builtin.include_tasks: validate_inputs.yml

- name: Check If vCenter Already Exists
  vmware.vmware.guest_info:
    hostname: "{{ provision_vcenter_hostname }}"
    username: "{{ provision_vcenter_username }}"
    password: "{{ provision_vcenter_password }}"
    port: "{{ provision_vcenter_port | default(omit) }}"
    validate_certs: "{{ provision_vcenter_validate_certs | default(omit) }}"
    name: "{{ provision_vcenter_vm_name }}"
  register: _vcenter_lookup

- name: Create Instance From ISO
  when: not _vcenter_lookup.guests
  block:
    - name: Gather Required OS Facts
      ansible.builtin.setup:
        gather_subset:
          - system
      when: ansible_os_family is not defined
    - name: Create Instance From ISO
      ansible.builtin.include_tasks: deploy_from_iso.yml
  always:
    - name: Remove The Installer Config JSON
      ansible.builtin.file:
        path: /tmp/vcsa_deployment_config.json
        state: absent
    - name: Unmount vCSA ISO
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - unmount_{{ ansible_os_family | lower }}.yml
            - unmount_default.yml
          paths:
            - os_specific_iso_actions

- name: Make Sure vCenter Appliance Is Powered On
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ provision_vcenter_hostname }}"
    username: "{{ provision_vcenter_username }}"
    password: "{{ provision_vcenter_password }}"
    port: "{{ provision_vcenter_port | default(omit) }}"
    validate_certs: "{{ provision_vcenter_validate_certs | default(omit) }}"
    datacenter: "{{ provision_vcenter_vc_target_datacenter | default(omit) }}"
    name: "{{ provision_vcenter_vm_name }}"
    state: powered-on

- name: Wait for the VSphere to be Reachable (=~ 180s)
  ansible.builtin.uri:
    method: HEAD
    validate_certs: false
    url: "https://{{ provision_vcenter_vm_network_hostname }}"
  retries: 100
  delay: 10
  until: _vcenter_uri_result is succeeded
  register: _vcenter_uri_result
