- name: Fetch the appliance information
  vmware.vmware.appliance_info:
    hostname: "{{ info_hostname }}"
    username: "{{ info_username }}"
    password: "{{ info_password }}"
    port: "{{ info_port | d(omit) }}"
    validate_certs: "{{ info_validate_certs | default(omit) }}"
    properties: "{{ info_appliance_gather }}"
  register: __appliance

- name: Write Appliance Results To File
  when: info_appliance_file
  block:
    - name: Make sure directory exists
      ansible.builtin.file: # noqa: risky-file-permissions
        path: "{{ info_appliance_file | dirname }}"
        state: "directory"
    - name: Create JSON file from fetched data
      ansible.builtin.copy:
        content: "{{ __appliance.appliance | to_json }}"
        dest: "{{ info_appliance_file }}"
        mode: "0644"
