- name: Guest info
  vmware.vmware.guest_info:
    hostname: "{{ info_hostname }}"
    username: "{{ info_username }}"
    password: "{{ info_password }}"
    port: "{{ info_port | d(omit) }}"
    validate_certs: "{{ info_validate_certs | default(omit) }}"
  register: __guests

- name: Write Guest Results To File
  when: info_guest_file
  block:
    - name: Make sure directory exists
      ansible.builtin.file: # noqa: risky-file-permissions
        path: "{{ info_guest_file | dirname }}"
        state: "directory"
    - name: Create JSON file from fetched data
      ansible.builtin.copy:
        content: "{{ __guests | to_json }}"
        dest: "{{ info_guest_file }}"
        mode: "0644"
