- name: Fetch the license information
  vmware.vmware.license_info:
    hostname: "{{ info_hostname }}"
    username: "{{ info_username }}"
    password: "{{ info_password }}"
    port: "{{ info_port | d(omit) }}"
    validate_certs: "{{ info_validate_certs | default(omit) }}"
  register: __license

- name: Write License Results To File
  when: info_license_file
  block:
    - name: Make sure directory exists
      ansible.builtin.file: # noqa: risky-file-permissions
        path: "{{ info_license_file | dirname }}"
        state: "directory"
    - name: Create JSON file from fetched data
      ansible.builtin.copy:
        content: "{{ __license.licenses | to_json }}"
        dest: "{{ info_license_file }}"
        mode: "0644"
