---
- name: Playbook to revert a VM state to a given snapshot
  hosts: all
  gather_facts: false

  roles:
    - role: cloud.vmware_ops.snapshot_management
      vars:
        snapshot_management_state: revert
