download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/sabre1041-eda-1.0.2.tar.gz
format_version: 1.0.0
name: eda
namespace: sabre1041
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.2
version_url: /api/v3/plugin/ansible/content/published/collections/index/sabre1041/eda/versions/1.0.2/
