---
- name: Playbook To Put An ESXi Host In Maintenance Mode
  hosts: all
  gather_facts: false

  roles:
    - role: cloud.vmware_ops.esxi_maintenance_mode
      vars:
        esxi_maintenance_mode_enable: true
